name: My First GitHub Actions

on:
  push:
    branches:
      - main   # change if your branch is different

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Python from system
      run: |
        python${{ matrix.python-version }} --version

    - name: Install dependencies
      run: |
        python${{ matrix.python-version }} -m pip install --upgrade pip
        python${{ matrix.python-version }} -m pip install pytest

    - name: Run tests
      run: |
        cd src
        python${{ matrix.python-version }} -m pytest addition.py
